"""

>>> from boto.support.layer1 import SupportConnection
>>> c = SupportConnection()
>>> x = c.describe_trusted_advisor_checks('en')
>>> for c in x['checks']:
...     if c['category'] == 'performance' and c['name'] == 'Service Limits':
...         sl = c
... 
>>> sl
{u'category': u'performance', u'metadata': [u'Region', u'Service', u'Limit Name', u'Limit Amount', u'Current Usage', u'Status'], u'description': u'Checks for usage that is more than 80% of the service limit. Values are based on a snapshot, so your current usage might differ. Limit and usage data can take up to 24 hours to reflect any changes. In some cases, your usage might be greater than the indicated limit for a period of time.<br>\n<br>\n<b>Alert Criteria</b><br>\nYellow: Usage is more than 80% of the service limit.<br>\n<br>\n<b>Recommended Action</b><br>\nIf you anticipate exceeding a service limit, open a case in Support Center to <a href="https://aws.amazon.com/support/createCase?type=service_limit_increase" target="_blank">request a limit increase</a>.<br>\n<br>\n<b>Additional Resources</b><br>\n<a href="https://aws.amazon.com/premiumsupport/ta-faqs/" target="_blank">Trusted Advisor FAQs</a><br/>\n<a href="http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html" target="_blank">AWS Service Limits</a><br/>\n<a href="https://console.aws.amazon.com/ec2/v2/home?#Limits:" target="_blank">EC2 Service Limits</a> (per region) in the Amazon EC2 console', u'name': u'Service Limits', u'id': u'eW7HH0l7J9'}

>>> r = conn.describe_trusted_advisor_check_result('eW7HH0l7J9')
>>> for x in r['result']:
...     print(x)
... 
checkId
status
flaggedResources
timestamp
resourcesSummary
categorySpecificSummary
>>> for t in r['result']['flaggedResources']:
...     print(t['metadata'][1], t['metadata'][2])
... 
(u'AutoScaling', u'Auto Scaling groups')
(u'AutoScaling', u'Auto Scaling groups')
(u'AutoScaling', u'Launch configurations')
(u'AutoScaling', u'Launch configurations')
(u'EBS', u'Active snapshots')
(u'EBS', u'Active volumes')
(u'EBS', u'Provisioned IOPS (SSD) storage (GiB)')
(u'EBS', u'Magnetic volume storage (GiB)')
(u'EBS', u'Provisioned IOPS')
(u'EC2', u'Elastic IP addresses (EIPs)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EC2', u'Reserved Instances - purchase limit (monthly)')
(u'EBS', u'General Purpose (SSD) volume storage (GiB)')
(u'VPC', u'VPCs')
(u'VPC', u'VPCs')
(u'VPC', u'Internet gateways')
(u'VPC', u'Internet gateways')
(u'ELB', u'Active load balancers')
(u'RDS', u'DB instances')
(u'RDS', u'Max auths per security group')
(u'RDS', u'DB security groups')
(u'RDS', u'DB security groups')
(u'RDS', u'Storage quota (GB)')
(u'RDS', u'DB snapshots per user')
(u'RDS', u'DB security groups')
(u'RDS', u'DB security groups')
(u'RDS', u'DB security groups')
(u'RDS', u'DB security groups')
(u'RDS', u'DB security groups')
(u'RDS', u'DB security groups')
(u'RDS', u'DB security groups')
>>> pprint.pprint(r['result'])
{u'categorySpecificSummary': {u'costOptimizing': {u'estimatedMonthlySavings': 0.0,
                                                  u'estimatedPercentMonthlySavings': 0.0}},
 u'checkId': u'eW7HH0l7J9',
 u'flaggedResources': [{u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'AutoScaling',
                                      u'Auto Scaling groups',
                                      u'100',
                                      u'31',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'7YaaSUFI3pISSczCq_KTLxAWJuV9GadOO7n94G5lEfU',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-west-2',
                                      u'AutoScaling',
                                      u'Auto Scaling groups',
                                      u'20',
                                      u'2',
                                      u'Green'],
                        u'region': u'us-west-2',
                        u'resourceId': u'4KauPhs6tHUY1hN5im0Uu0-a87yWLXrgk5NP8KNfTX0',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-west-2',
                                      u'AutoScaling',
                                      u'Launch configurations',
                                      u'100',
                                      u'2',
                                      u'Green'],
                        u'region': u'us-west-2',
                        u'resourceId': u'frIDxQZseHOHU1d7RNRvW-teKy-ShO97N65FY8tW55Q',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'AutoScaling',
                                      u'Launch configurations',
                                      u'200',
                                      u'116',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'KQDe_j-P1BQhQP73Uj6hjzwoR_YfCf9KI0_ffmBAoqw',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'EBS',
                                      u'Active snapshots',
                                      u'10000',
                                      u'823',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'bihFpPoWs1k-Ner9Hk9Z4e5qvD84lVeTuBo656LVzik',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'EBS',
                                      u'Active volumes',
                                      u'5000',
                                      u'2457',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'N16i53KbHBnt2GhG9CLM0OwK46GFND9jZ89-cHQBuEc',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'EBS',
                                      u'Provisioned IOPS (SSD) storage (GiB)',
                                      u'20480',
                                      u'3200',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'M9rq16aS5kU1uT-NYik_rhoBsZd9B6YTPsD47PoqNWc',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'EBS',
                                      u'Magnetic volume storage (GiB)',
                                      u'30720',
                                      u'21305',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'OuokRze3iU6oulvLpXVn36mSNWHEMk6fVQgGBuql-ck',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'EBS',
                                      u'Provisioned IOPS',
                                      u'40000',
                                      u'5600',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'4aDDM6P89nc52mG9HseBsFuFh-Fw69oIqJNKaAbGUS4',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'EC2',
                                      u'Elastic IP addresses (EIPs)',
                                      u'10',
                                      u'5',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'Aao6OoW_B5TOqRIFJ5v9LM5iU0Z2d-fQZzE2JefFty8',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'eu-west-1',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'eu-west-1',
                        u'resourceId': u'DIXQz-a5iLrYeheHGF9tq04_ShDujEVEV8iiJH-RJJY',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'ap-southeast-1',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'ap-southeast-1',
                        u'resourceId': u'gBs5-AyWNCy-IE8yD5wxI2z6aFjDZiHJVFhqKvGhcso',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'ap-southeast-2',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'ap-southeast-2',
                        u'resourceId': u'vDUJRMENyuIbWz6CGho8zJTKBfz4R9joNKGj2uROXE8',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'eu-central-1',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'eu-central-1',
                        u'resourceId': u'8SaXIx3X6Psjtj0-K2vaM8n8I3N-vu9TOkR584El3SA',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'ap-northeast-1',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'ap-northeast-1',
                        u'resourceId': u'uq3RHLCT0Mga_VtxGSFyh7la4zVeMgf_QwLsenXg2O4',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'cK7Lus-uGFoM7nkzJ8vzKaUY61ecw3N3hq2UYvZc5Vw',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'sa-east-1',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'sa-east-1',
                        u'resourceId': u'TdFdQ5X6xESQ_bKVSSML4YrWDMI3MPGtcdwJ999T52A',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-west-1',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'us-west-1',
                        u'resourceId': u'gMthpwWkhOrZkzNcsIfZsRjpOPEAuDtyNTHZrHcFOJY',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-west-2',
                                      u'EC2',
                                      u'Reserved Instances - purchase limit (monthly)',
                                      u'20',
                                      None,
                                      u'Green'],
                        u'region': u'us-west-2',
                        u'resourceId': u'XGU9uJxjcgdmcnbbeLGUDOgdBgIpkf2-jPdo9gEa0k0',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'EBS',
                                      u'General Purpose (SSD) volume storage (GiB)',
                                      u'30720',
                                      u'4461',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'qjmozeN7w4JI_6TzhUNUI4JJrO6VUWf0YI1xK0_i1nk',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'VPC',
                                      u'VPCs',
                                      u'5',
                                      u'4',
                                      u'Yellow'],
                        u'region': u'us-east-1',
                        u'resourceId': u'Q_rbEiInPnbO_o7cRUytRcysVu4zRMTB9nXiWA2KAXc',
                        u'status': u'warning'},
                       {u'isSuppressed': False,
                        u'metadata': [u'eu-central-1',
                                      u'VPC',
                                      u'VPCs',
                                      u'5',
                                      u'1',
                                      u'Green'],
                        u'region': u'eu-central-1',
                        u'resourceId': u'_puwFq-mvr6QNiDTkzUKfeYgSgrpPmlZ81KweQuL-Uk',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'VPC',
                                      u'Internet gateways',
                                      u'5',
                                      u'4',
                                      u'Yellow'],
                        u'region': u'us-east-1',
                        u'resourceId': u'ijycDAOMI5X7hrMkbgR8sQ1-n4Ouo-wmYx2E8epz9nc',
                        u'status': u'warning'},
                       {u'isSuppressed': False,
                        u'metadata': [u'eu-central-1',
                                      u'VPC',
                                      u'Internet gateways',
                                      u'5',
                                      u'1',
                                      u'Green'],
                        u'region': u'eu-central-1',
                        u'resourceId': u'jEOMnXHwvg9NbE6q4ZC9nWULOXy5brS8n4PhmHjtnB4',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'ELB',
                                      u'Active load balancers',
                                      u'50',
                                      u'39',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'Z_y-6_GAy9Ew00KFVJlVrSnJjD4YMXlqKTD8Xh7VNJY',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'RDS',
                                      u'DB instances',
                                      u'40',
                                      u'23',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'xjP94TOVQ2Ha_nV67gClVlcT2PFfoFYE2lnM7xu65Wg',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'RDS',
                                      u'Max auths per security group',
                                      u'20',
                                      u'1',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'EZv2GqRR8rh2IPSwd2tM3ybMzlm9Fy1VVeSCSVjib1g',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'eu-west-1',
                                      u'RDS',
                                      u'DB security groups',
                                      u'25',
                                      u'1',
                                      u'Green'],
                        u'region': u'eu-west-1',
                        u'resourceId': u'l52Jfssec7BH_tZPf2uThmauo_ltrchEDkKHipVVHKI',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'RDS',
                                      u'DB security groups',
                                      u'50',
                                      u'26',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'HiME4m44HnYKVq-xh2Cx3yKDx96-Orwm-D5tpK90ik8',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'RDS',
                                      u'Storage quota (GB)',
                                      u'100000',
                                      u'1125',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'5ZK4wtR2OH6F_2gFHMWDw1CTwbhOk8i_WrcLftzfYew',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-east-1',
                                      u'RDS',
                                      u'DB snapshots per user',
                                      u'50',
                                      u'33',
                                      u'Green'],
                        u'region': u'us-east-1',
                        u'resourceId': u'RrXYkGjlEwZYQjN3mCT52kve5m7WNjn8cLOM7prQw_o',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'eu-central-1',
                                      u'RDS',
                                      u'DB security groups',
                                      u'20',
                                      u'1',
                                      u'Green'],
                        u'region': u'eu-central-1',
                        u'resourceId': u'Sd_Be-OgR0YR_ir5qyaXuexY6osWRrRYAzJyheaGMqI',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-west-1',
                                      u'RDS',
                                      u'DB security groups',
                                      u'25',
                                      u'1',
                                      u'Green'],
                        u'region': u'us-west-1',
                        u'resourceId': u'WLMHrhNRk9FDkUeuktV8pbZZbQigsMNxsdWYA1exI_Q',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'sa-east-1',
                                      u'RDS',
                                      u'DB security groups',
                                      u'25',
                                      u'1',
                                      u'Green'],
                        u'region': u'sa-east-1',
                        u'resourceId': u'1Q10qanaAxZIoxmrmLaJmif8cglI0AiB8lp4KeCtGF4',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'us-west-2',
                                      u'RDS',
                                      u'DB security groups',
                                      u'25',
                                      u'1',
                                      u'Green'],
                        u'region': u'us-west-2',
                        u'resourceId': u'KCA0zWdjmf2PnY1G8_VyOiZBNegPToSrw6NTuGdbXbM',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'ap-northeast-1',
                                      u'RDS',
                                      u'DB security groups',
                                      u'25',
                                      u'1',
                                      u'Green'],
                        u'region': u'ap-northeast-1',
                        u'resourceId': u'xdBzydQTF9qbtADZb0TFJD8lcUfDiUdtnuvvSSYq6Kw',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'ap-southeast-1',
                                      u'RDS',
                                      u'DB security groups',
                                      u'25',
                                      u'1',
                                      u'Green'],
                        u'region': u'ap-southeast-1',
                        u'resourceId': u'j2vYubqZhU0c_PMGMwuxQDE40g_uZKCiBDrYrfoxzbY',
                        u'status': u'ok'},
                       {u'isSuppressed': False,
                        u'metadata': [u'ap-southeast-2',
                                      u'RDS',
                                      u'DB security groups',
                                      u'25',
                                      u'1',
                                      u'Green'],
                        u'region': u'ap-southeast-2',
                        u'resourceId': u'fB8VeEfCzEMnuSxDyvvnjtU6d3SpTy4lZAF5GH1CFAU',
                        u'status': u'ok'}],
 u'resourcesSummary': {u'resourcesFlagged': 2,
                       u'resourcesIgnored': 0,
                       u'resourcesProcessed': 38,
                       u'resourcesSuppressed': 0},
 u'status': u'warning',
 u'timestamp': u'2015-06-07T02:35:02Z'}
>>> 
"""